// Second, broader release log (feature/codename framing) pasted 2026-09-22. Confirmed by the user
// to be fully merged/live, including the "staging queue" tail. Web only; two iOS-only items dropped.
window.DASH_RELEASES_LOG = [
  { date: '2026-06-02', tag: 'pdpl',                    what: 'Upgraded Product Detail Page layouts for better mobile layout ratios' },
  { date: '2026-06-02', tag: 'tier-be',                  what: 'Backend-to-frontend tier mapping logic to dynamically adjust user privilege widgets' },
  { date: '2026-06-02', tag: 'DynamicLink',              what: 'Deep-linking schemas for routing from social assets directly to checkout screens' },
  { date: '2026-06-04', tag: 'cart-checkout-event',      what: 'Custom event tracking covering step-by-step cart interactions' },
  { date: '2026-06-04', tag: 'pdp-show-config',          what: 'Master config toggle to conditionally show or hide course packages on the PDP' },
  { date: '2026-06-05', tag: 'subs-success-journey',     what: 'New member success flow and onboarding screens' },
  { date: '2026-06-05', tag: 'fbmetaTr',                 what: 'Fixed duplicated Facebook conversion tracking parameters on payment checkout' },
  { date: '2026-06-05', tag: 'tier-add',                 what: 'Enhanced pricing tier input flows on checkout views' },
  { date: '2026-06-08', tag: 'ga4chh',                   what: 'Patched GA4 e-commerce tracking bugs during checkout steps' },
  { date: '2026-06-08', tag: 'showPdpCtaFix',             what: 'Fixed PDP CTA button layout breaks on older iOS models' },
  { date: '2026-06-08', tag: 'newTempBe',                what: 'Render modules for newly formatted course templates' },
  { date: '2026-06-11', tag: 'dg-ee-mixpanel',           what: 'Unified telemetry triggers on DG-EE pages' },
  { date: '2026-06-15', tag: 'release 15-06-2026',        what: '🚀 Payment Phase 2 core launch: multi-currency checkout, Apple Pay, pricing detail widgets' },
  { date: '2026-06-16', tag: 'recording-limit',          what: 'Client-side limits on live-recording access after class limits reached' },
  { date: '2026-06-16', tag: 'addedDeeplinkForSuccess',  what: 'Direct route configuration to the order success page' },
  { date: '2026-06-18', tag: 'tnc',                      what: 'Updated terms-of-use acceptance prompts' },
  { date: '2026-06-18', tag: 'reviewProduct',            what: 'Responsive review-rating slider on PDP layouts' },
  { date: '2026-06-22', tag: 'dg-ee-event-fix',          what: 'Minor payload corrections on in-app trackers' },
  { date: '2026-06-22', tag: 'offline-tier-date',        what: 'Contextual pricing adjustments based on scheduled session dates' },
  { date: '2026-06-26', tag: 'subscription-cancellation-fix', what: 'Redesigned member cancellation funnel with confirmation feedback steps' },
  { date: '2026-06-26', tag: 'guest-sdk-new',            what: 'Real-time token hydration for guest participants (Zoom SDK)' },
  { date: '2026-07-01', tag: 'pastSessRec',              what: 'Selectors allowing members to review historical class recordings' },
  { date: '2026-07-02', tag: 'release/2-jul-2026',        what: '🚀 Leader-profile notification modules (leader-crm-notif)' },
  { date: '2026-07-02', tag: 'newPdpUiChanges',          what: 'Consolidated visual components on PDP layouts for consistent spacing/typography' },
  { date: '2026-07-03', tag: 'energyExchangepric',       what: 'Real-time discount calculation for the Energy Exchange layout' },
  { date: '2026-07-03', tag: 'diff-platform-fee',        what: 'Explicit checkout fee breakdown during booking' },
  { date: '2026-07-06', tag: 'url-restruct',             what: 'SEO-optimized canonical routes across course/listing directories' },
  { date: '2026-07-06', tag: 'pdpRails',                 what: 'Horizontal scrolling rails for recommended sessions on the PDP' },
  { date: '2026-07-13', tag: 'one on one slot check',     what: '🚀 Real-time booking verification to prevent double-booking on 1:1 sessions' },
  { date: '2026-07-15', tag: 'hostpaneljoin',            what: 'Patched host browser-routing failures joining meetings via Web SDK' },
  { date: '2026-07-15', tag: 'url-short-cache',          what: 'Edge caching to speed up URL-shortener lookups' },
  { date: '2026-07-20', tag: 'home-d-web',               what: '🌟 MAJOR: desktop web homepage redesign (responsive grids, category browsing)' },
  { date: '2026-07-21', tag: 'time-slot-soft-delete',    what: 'Automated state-clearing when a booking slot is soft-deleted' },
  { date: '2026-07-21', tag: 'wa-message-id',            what: 'WhatsApp transmission IDs added to checkout tracing' },
  { date: '2026-07-23', tag: 'authv3_50',                what: 'Auth V3 phase 2: new quick-checkout login flow to 50% of web traffic' },
  { date: '2026-07-23', tag: 'pdprailextension',         what: 'Deep-linked category rails at the bottom of the PDP' },
  { date: '2026-07-28', tag: 'home-topfold',             what: '🚀 Redesigned, high-conversion top fold for the main homepage' },
  { date: '2026-07-28', tag: null,                        what: 'Mobile/Safari container-width rendering hotfixes' },
  { date: '2026-07-29', tag: 'revalidateServerFix',      what: 'Fixed stale PDP data via precise Next.js ISR revalidation triggers' },
  { date: '2026-08-03', tag: 'auth-100',                 what: 'Auth V3 phase 3: 100% rollout of the new login flow' },
  { date: '2026-08-04', tag: 'AB pdp cta text and free gift addon', what: '🚀 A/B test: PDP CTA text variants + free-gift addon bundles on checkout' },
  { date: '2026-08-07', tag: 'newFooter',                what: '🚀 Redesigned footer + 1% platform-fee indicator on 1:1 booking panels' },
  { date: '2026-08-10', tag: null,                        what: 'Unfilled-slots vacancy indicator on course panels' },
  { date: '2026-08-10', tag: 'heroScrollFix',             what: 'Improved touch-swipe responsiveness of the homepage hero carousel' },
  { date: '2026-08-13', tag: 'offline venues',            what: '🚀 Physical offline-venue cards for in-person class booking at checkout' },
  { date: '2026-08-14', tag: 'release 14-08-2026',        what: '🚀 Discovery overhaul: new listings layout V2 + leader "About Me" pages + hamburger nav' },
  { date: '2026-08-17', tag: 'staging into main',         what: '🚀 Removed legacy slot-booking constraints; build optimization' },
  { date: '2026-08-18', tag: 'default listing card change', what: 'Restyled course listing cards, improving badge visibility' },
  { date: '2026-08-18', tag: 'bottom sheet multicity',    what: 'Bottom-sheet city filter for physical classes' },
  { date: '2026-08-18', tag: 'taro meta exp',             what: 'Analytics event tracking on Tarot consult grids' },
  { date: '2026-08-18', tag: 'one on one navigation fix', what: 'Fixed route-freeze glitches on 1:1 navigation transitions' },
  { date: '2026-08-24', tag: 'add checkout leader user query', what: 'Recommendation triggers to suggest class slots on successful booking screens' },
  { date: '2026-08-24', tag: 'leader campaign cool down', what: 'CRM communication cool-downs to prevent messaging fatigue' },
  { date: '2026-09-01', tag: null,                        what: 'Richer visual branding on collection landing layouts' },
  { date: '2026-09-01', tag: 'one on one slot fetch',     what: 'Refactored 1:1 booking retrieval, reducing loading states on date switches' },
  { date: '2026-09-07', tag: 'auto suggest new login',    what: 'Autocomplete predictive helper inputs on registration forms' },
  { date: '2026-09-10', tag: 'faithbased layout on other tech', what: 'Master visual theme switch for spiritual layouts' },
  { date: '2026-09-10', tag: 'pinned',                    what: 'Pin favourite classes/banners to the top of listings' },
  { date: '2026-09-21', tag: 'tarot-payment-page',        what: 'Dedicated checkout sheet for tarot consultations' },
  { date: '2026-09-21', tag: 'PdpSequence',               what: 'Fixed chronological timeline rendering for multi-day schedules' },
  { date: '2026-09-21', tag: 'pdpCtaDateChanges',         what: 'Adaptive CTA label text based on the selected class date' }
];
